import { db } from './db'
import type { Ingredient } from './types'

type SeedIngredient = Omit<Ingredient, 'id' | 'createdAt'>

const grains: SeedIngredient[] = [
  { name: '쌀미음', category: '곡물', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '현미', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['고소함', '담백함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '백미', category: '곡물', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '찹쌀', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함', '고소함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '보리', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '귀리', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '오트밀', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '차조', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '기장', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '수수', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '흑미', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '율무', category: '곡물', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '메밀', category: '곡물', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: true },
  { name: '좁쌀', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '옥수수가루', category: '곡물', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
]

const vegetables: SeedIngredient[] = [
  { name: '단호박', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['단맛'], nutrientTags: ['비타민A', '식이섬유'], isAllergen: false },
  { name: '브로콜리', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['비타민C', '식이섬유'], isAllergen: false },
  { name: '당근', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '시금치', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['철분', '비타민A'], isAllergen: false },
  { name: '애호박', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '양배추', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['비타민C', '식이섬유'], isAllergen: false },
  { name: '완두콩', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['단백질', '식이섬유'], isAllergen: false },
  { name: '감자', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '고구마', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['단맛'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '오이', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '비트', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['철분'], isAllergen: false },
  { name: '무', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '배추', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '알배추', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '청경채', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '콜리플라워', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '파프리카', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '토마토', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '방울토마토', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '가지', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '셀러리', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['쌉쌀함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '아스파라거스', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '연근', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '우엉', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '도라지', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '미역', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '다시마', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '김', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['철분'], isAllergen: false },
  { name: '표고버섯', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '새송이버섯', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '팽이버섯', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '양송이버섯', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '애느타리버섯', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '목이버섯', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '부추', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '근대', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['철분'], isAllergen: false },
  { name: '열무', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '얼갈이배추', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '콩나물', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '숙주나물', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '마', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '야콘', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '케일', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['쌉쌀함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '콜라비', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '순무', category: '채소', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '죽순', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '미나리', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '쑥갓', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['쌉쌀함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '아욱', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '취나물', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '고사리', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '두릅', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '브로콜리새싹', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '무순', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '알팔파새싹', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '파슬리', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '로메인상추', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '양상추', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '치커리', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['쌉쌀함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '옥수수', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['탄수화물'], isAllergen: false },
  { name: '그린빈', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '완두순', category: '채소', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '생강', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '마늘', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['감칠맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '양파', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '대파', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '실파', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '쪽파', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '달래', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '냉이', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '곤드레나물', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '참나물', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '방풍나물', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '돌나물', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '비름나물', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['칼슘'], isAllergen: false },
  { name: '갓', category: '채소', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '유채나물', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '고구마순', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '토란', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '오크라', category: '채소', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['식이섬유'], isAllergen: false },
]

const fruits: SeedIngredient[] = [
  { name: '사과', category: '과일', unit: 'g', minStage: '초기', tasteTags: ['단맛', '신맛'], nutrientTags: ['식이섬유', '비타민C'], isAllergen: false },
  { name: '바나나', category: '과일', unit: 'g', minStage: '초기', tasteTags: ['단맛'], nutrientTags: ['탄수화물', '식이섬유'], isAllergen: false },
  { name: '배', category: '과일', unit: 'g', minStage: '초기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '딸기', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛', '신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '블루베리', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛', '신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '복숭아', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '천도복숭아', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '감', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '홍시', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '곶감', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '포도', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '청포도', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '수박', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '참외', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '멜론', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '키위', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: true },
  { name: '골드키위', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: true },
  { name: '자두', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '살구', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '망고', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: true },
  { name: '애플망고', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: true },
  { name: '파인애플', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '오렌지', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '귤', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '한라봉', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '천혜향', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '레드향', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '자몽', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '체리', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '무화과', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '석류', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '아보카도', category: '과일', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: false },
  { name: '레몬', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '라임', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '크랜베리', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '라즈베리', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '블랙베리', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '대추', category: '과일', unit: 'g', minStage: '후기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '유자', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '앵두', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛', '단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '파파야', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민A'], isAllergen: false },
  { name: '용과', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['식이섬유'], isAllergen: false },
  { name: '망고스틴', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '패션프루트', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['신맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '스타프루트', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '오디', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['철분'], isAllergen: false },
  { name: '아로니아', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['쌉쌀함'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '구아바', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
  { name: '리치', category: '과일', unit: 'g', minStage: '완료기', tasteTags: ['단맛'], nutrientTags: ['비타민C'], isAllergen: false },
]

const meats: SeedIngredient[] = [
  { name: '닭고기 안심', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['담백함', '감칠맛'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '소고기 안심', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '철분'], isAllergen: false },
  { name: '닭다리살', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '닭가슴살', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '소고기 우둔살', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '철분'], isAllergen: false },
  { name: '소고기 다짐육', category: '육류', unit: 'g', minStage: '중기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '철분'], isAllergen: false },
  { name: '소고기 사태', category: '육류', unit: 'g', minStage: '후기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '철분'], isAllergen: false },
  { name: '돼지고기 안심', category: '육류', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '돼지고기 등심', category: '육류', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '오리고기', category: '육류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '지방'], isAllergen: false },
  { name: '양고기', category: '육류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '칠면조고기', category: '육류', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: false },
  { name: '채끝살', category: '육류', unit: 'g', minStage: '후기', tasteTags: ['감칠맛'], nutrientTags: ['단백질', '철분'], isAllergen: false },
]

const seafood: SeedIngredient[] = [
  { name: '흰살생선(대구)', category: '어류', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '명태', category: '어류', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '광어', category: '어류', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '가자미', category: '어류', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '도미', category: '어류', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '연어', category: '어류', unit: 'g', minStage: '후기', tasteTags: ['감칠맛', '고소함'], nutrientTags: ['지방', '단백질'], isAllergen: true },
  { name: '참치', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '새우', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '굴', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['철분'], isAllergen: true },
  { name: '관자', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '문어', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '오징어', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '홍합', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['철분'], isAllergen: true },
  { name: '바지락', category: '어류', unit: 'g', minStage: '완료기', tasteTags: ['감칠맛'], nutrientTags: ['철분'], isAllergen: true },
  { name: '멸치가루', category: '어류', unit: 'g', minStage: '후기', tasteTags: ['감칠맛'], nutrientTags: ['칼슘'], isAllergen: true },
]

const dairy: SeedIngredient[] = [
  { name: '아기치즈', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['칼슘', '지방'], isAllergen: true },
  { name: '플레인 요거트', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['신맛'], nutrientTags: ['칼슘', '단백질'], isAllergen: true },
  { name: '우유', category: '유제품', unit: 'ml', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['칼슘'], isAllergen: true },
  { name: '생크림', category: '유제품', unit: 'ml', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: true },
  { name: '버터', category: '유제품', unit: 'g', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: true },
  { name: '무염버터', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: true },
  { name: '코티지치즈', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['단백질', '칼슘'], isAllergen: true },
  { name: '리코타치즈', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['단백질', '칼슘'], isAllergen: true },
  { name: '그릭요거트', category: '유제품', unit: 'g', minStage: '후기', tasteTags: ['신맛'], nutrientTags: ['단백질', '칼슘'], isAllergen: true },
]

const others: SeedIngredient[] = [
  { name: '두부', category: '기타', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질', '칼슘'], isAllergen: true },
  { name: '달걀노른자', category: '기타', unit: '개', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['단백질', '지방'], isAllergen: true },
  { name: '순두부', category: '기타', unit: 'g', minStage: '중기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '달걀(전란)', category: '기타', unit: '개', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['단백질', '지방'], isAllergen: true },
  { name: '달걀흰자', category: '기타', unit: '개', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '렌틸콩', category: '기타', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질', '식이섬유'], isAllergen: false },
  { name: '병아리콩', category: '기타', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['단백질', '식이섬유'], isAllergen: false },
  { name: '검은콩', category: '기타', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '강낭콩', category: '기타', unit: 'g', minStage: '후기', tasteTags: ['담백함'], nutrientTags: ['단백질', '식이섬유'], isAllergen: false },
  { name: '서리태', category: '기타', unit: 'g', minStage: '후기', tasteTags: ['고소함'], nutrientTags: ['단백질'], isAllergen: true },
  { name: '아몬드가루', category: '기타', unit: 'g', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['지방', '단백질'], isAllergen: true },
  { name: '땅콩버터', category: '기타', unit: 'g', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['지방', '단백질'], isAllergen: true },
  { name: '참기름', category: '기타', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: false },
  { name: '들기름', category: '기타', unit: 'g', minStage: '중기', tasteTags: ['고소함'], nutrientTags: ['지방'], isAllergen: false },
  { name: '올리브오일', category: '기타', unit: 'g', minStage: '초기', tasteTags: ['담백함'], nutrientTags: ['지방'], isAllergen: false },
  { name: '치아씨드', category: '기타', unit: 'g', minStage: '완료기', tasteTags: ['담백함'], nutrientTags: ['식이섬유', '지방'], isAllergen: false },
  { name: '아마씨가루', category: '기타', unit: 'g', minStage: '완료기', tasteTags: ['고소함'], nutrientTags: ['지방', '식이섬유'], isAllergen: false },
]

const seedIngredients: SeedIngredient[] = [
  ...grains,
  ...vegetables,
  ...fruits,
  ...meats,
  ...seafood,
  ...dairy,
  ...others,
]

/**
 * Adds any ingredient from the master seed list that isn't already present (by name),
 * and creates a default profile on first run. Safe to call on every app load.
 */
export async function seedIfEmpty() {
  const existing = await db.ingredients.toArray()
  const existingNames = new Set(existing.map((i) => i.name.toLowerCase()))
  const missing = seedIngredients.filter((ing) => !existingNames.has(ing.name.toLowerCase()))

  if (missing.length > 0) {
    const now = new Date().toISOString()
    await db.ingredients.bulkAdd(missing.map((ing) => ({ ...ing, createdAt: now })))
  }

  const profileCount = await db.profile.count()
  if (profileCount === 0) {
    await db.profile.add({ birthDate: '', allergyIngredientIds: [], avoidIngredientIds: [], mealTargetGrams: {} })
  }
}
